metadata/unpackaged/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The project this milestone is assigned to. If this is a sub-milestone this field is empty.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/unpackaged/objects/Milestone1_Project__c.object
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/unpackaged/classes/Milestone1_Milestone_Batch_Delete.cls
/**
* Batchable class to manage milestone deletes
*/
global with sharing class Milestone1_Milestone_Batch_Delete implements Database.Batchable<sObject>{
	
	global final List<Milestone1_Milestone__c> milestones;
	
	global Milestone1_Milestone_Batch_Delete( List<Milestone1_Milestone__c> ms ){
		this.milestones = ms;
	}

	global Database.QueryLocator start(Database.BatchableContext BC){
    	Set<Id> ids = new Set<Id>();
    	
    	for(Milestone1_Milestone__c m : milestones){
    		ids.add( m.Id );
    	}
    	
		return Database.getQueryLocator( [SELECT Id FROM Milestone1_Milestone__c WHERE Id IN :ids] );
	}

	global void execute(Database.BatchableContext BC, List<sObject> milestoneScope){
		delete milestoneScope;
	}

	global void finish(Database.BatchableContext BC){}
	
	
	public static testmethod void testMilestoneBatchDelete(){
		// Create a project with milestones
		Milestone1_Project__c         project = Milestone1_Test_Utility.sampleProject('My Test Project'); 
		List<Milestone1_Milestone__c> mList   = new List<Milestone1_Milestone__c>();
		
		insert project;
		
		for(Integer i = 0; i < 200; i++){
			mList.add( Milestone1_Test_Utility.sampleMilestone(project.Id, null, 'My Test Milestone ' + i) );
		}
		
		insert mList;
		
		Test.StartTest();
		Database.executeBatch( new Milestone1_Milestone_Batch_Delete(mList) );
		Test.StopTest();

		// Test records were deleted
		Integer milestonesCount = [SELECT count() FROM Milestone1_Milestone__c WHERE Project__c = :project.Id];
		 
		System.assertEquals( 0, milestonesCount );
	}
}