metadata/objects/PPCommonRequestParameters__c.object
<CustomObject>
    <fields>
        <fullName>ApplicationName__c</fullName>
        <description>Your Application&apos;s Identification, such as the name of your application.</description>
        <inlineHelpText>Your Application&apos;s Identification, such as the name of your application.</inlineHelpText>
        <label>ApplicationName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CurrencyCode__c</fullName>
        <description>The currency code</description>
        <inlineHelpText>The currency code</inlineHelpText>
        <label>CurrencyCode</label>
        <picklist>
            <picklistValues>
                <fullName>AUD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CZK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DKK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HKD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HUF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ILS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JPY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MXN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PHP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GBP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SGD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TWD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DetailLevel__c</fullName>
        <description>The level of detail required by the client application for component such as Item, Transaction.</description>
        <inlineHelpText>The level of detail required by the client application for component such as Item, Transaction.</inlineHelpText>
        <label>DetailLevel</label>
        <picklist>
            <picklistValues>
                <fullName>ReturnAll</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FeePayer__c</fullName>
        <description>The payer of PayPal fees</description>
        <inlineHelpText>The payer of PayPal fees</inlineHelpText>
        <label>FeePayer</label>
        <picklist>
            <picklistValues>
                <fullName>SENDER</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PRIMARYRECEIVER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EACHRECEIVER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SECONDARYONLY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>en_US</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PayPal Common Request Parameters</label>
    <nameField>
        <label>PPCommonRequestParameters Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PayPal Common Request Parameters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/unpackaged/classes/PPCommonRequestParameters.cls
public class PPCommonRequestParameters {

	public class PPCommonRequestParametersException extends Exception {}
    PPCommonRequestParameters__c paramsObj;
	public string ApplicationName {get {return paramsObj.ApplicationName__c;} private set;} 
    public string CurrencyCode {get {return paramsObj.CurrencyCode__c;} private set;}
    public string DetailLevel {get {return paramsObj.DetailLevel__c;} private set;}
    public string FeePayer {get {return paramsObj.FeePayer__c;} private set;}
    public string Language {get {return paramsObj.Language__c;} private set;}    
    
    public PPCommonRequestParameters(string name) {
    	try{
    		paramsObj = [select ApplicationName__c,CurrencyCode__c,DetailLevel__c,FeePayer__c,Language__c,id from PPCommonRequestParameters__c where name = :name limit 1];
    		// all parameters are required    		
    	}catch(QueryException qex){
    		System.debug('Error when query PPCommonRequestParameters object - did not find any PPCommonRequestParameters with name of ['+name+']');
    		throw new PPCommonRequestParametersException('Error when query PPCommonRequestParameters object - did not find any PPCommonRequestParameters with name of ['+name+']');
    	}
    }
    
    static testmethod void testInstance() {
		try{
			PPCommonRequestParameters k = new PPCommonRequestParameters('nonexistentname');
		}catch(PPCommonRequestParametersException ex){
			system.debug('here: ' +ex.getTypeName());
		   	system.assert(ex.getTypeName().contains('PPCommonRequestParameters.PPCommonRequestParametersException'));
		   	
		}
		
		// test cases for 3_TOKEN Credentials
		PPCommonRequestParameters__c t1 = new PPCommonRequestParameters__c(  ApplicationName__c='DUMMY-APP',CurrencyCode__c='USD',DetailLevel__c='ReturnAll',FeePayer__c='SENDER',Language__c='en_US', name='test' );
		insert t1;
		PPCommonRequestParameters k = new PPCommonRequestParameters('test');
		system.assert(k.ApplicationName == 'DUMMY-APP');
		system.assert(k.CurrencyCode == 'USD');
		system.assert(k.DetailLevel == 'ReturnAll');
		system.assert(k.FeePayer == 'SENDER');
		system.assert(k.Language == 'en_US');
	}

}